# Generated by Django 3.2.6 on 2021-08-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='assoc_account',
            new_name='associated_account',
        ),
    ]
